



#define SESSION_TRAVERSAL_UTILITIES_FOR_NAT_MAGIC_COOKIE "\x21\x12\xa4\x42"
#define SESSION_TRAVERSAL_UTILITIES_FOR_NAT_CANONICAL_REQ_PREFIX "\x00\x01\x00\x00" SESSION_TRAVERSAL_UTILITIES_FOR_NAT_MAGIC_COOKIE
